### ISSUE TITLE
fuse library and mounting an external option not a valid option for attendees

### ISSUE THREAD

**Issue by thedamian** [sammydeprez/gai-workshop-2023#2]
The option in the "setup.py" where you're mounting the drive to pull a json that's available from a fetch has to be rethought.
1) because the fuse library isn't compatible with windows.  And connecting to a notebook in WSL is complicated
2) Even if you have Mac or Linux we don't have access to the endpoint.
3) Also everyone will be at universities and bootcamp locations and 50 attendees all downloading one 1.5GB CSV file is not doable (unles syou wait hours)

May I suggest changing the loading to a local file as I'll have the metadata.csv file in a thumb drive or local share to download onto each attendees computer.

Here's the error when I try to "mount()" your drive. 

![image](https://user-images.githubusercontent.com/2957660/221225707-f16b1d67-0dab-4f0e-8e72-118d9ae9db26.png)

**Comment by sammydeprez** [comment]
Hi @thedamian , all these notebooks need to be run in the Azure ML environment, so please upload your notebooks as described in the guide. And execute them from there. None of the tasks will work locally, because then you need to setup also a connectionstring to the workspace

**Comment by thedamian** [comment]
Thank you for replying @sammydeprez 
I jumped right into running it locally and even have fixes so it can be run locally. and I'm seeing here that it's not required. 
I'm going to follow the official workshop. 

Thank you for your comments. I will close the issue now.
